apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-credentials
  labels: {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  database: {{ .Values.postgres.database | quote }}
  user: {{ .Values.postgres.user | quote }}
  password: {{ include "app.dbPassword" . | quote }}
